version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: et-db
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "et-vol:/var/lib/postgresql/data"

volumes:
  et-vol:
